
delete from kbo_stat.tb_betman_sd_game_anal_allocation;
             
INSERT INTO kbo_stat.tb_betman_sd_game_anal_allocation
SELECT
            A.GAME_NUMBER,
            A.SPORT_TYPE,
            A.LEAGUE,
            A.BET_OPTION,
            A.HOME_TEAM,
            A.AWAY_TEAM,
            A.ALLOCATION_WIN,
            A.ALLOCATION_DRAW,
            A.ALLOCATION_LOSE,
            MAX(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) AS WINLEAGUETOTALGAMES,
            MAX(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) AS WINLEAGUEHITGAMES,
            MAX(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_RATE ELSE NULL END) AS WINLEAGUEHITRATE,
            MAX(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) AS DRAWLEAGUETOTALGAMES,
            MAX(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) AS DRAWLEAGUEHITGAMES,
            MAX(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_RATE ELSE NULL END) AS DRAWLEAGUEHITRATE,
            MAX(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) AS LOSELEAGUETOTALGAMES,
            MAX(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) AS LOSELEAGUEHITGAMES,
            MAX(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_RATE ELSE NULL END) AS LOSELEAGUEHITRATE,
            SUM(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) AS WINTOTALGAMES,
            SUM(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) AS WINHITGAMES,
            ROUND(SUM(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) / SUM(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) , 2 ) AS WINHITRATE,
            SUM(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) AS DRAWTOTALGAMES,
            SUM(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) AS DRAWHITGAMES,
            ROUND( SUM(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) / SUM(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) ,2 ) AS DRAWHITRATE,
            SUM(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) AS LOSETOTALGAMES,
            SUM(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) AS LOSEHITGAMES,
            ROUND(SUM(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) / SUM(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) ,2 ) AS LOSEHITRATE,

((  ( MAX(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_RATE ELSE NULL END) ) * A.ALLOCATION_WIN ) - 1 ) * 10000 AS win_le_ev,

(( ( MAX(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_RATE ELSE NULL END) ) * A.ALLOCATION_DRAW ) - 1 ) * 10000 AS draw_le_ev,

( (( MAX(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.LEAGUE = B.LEAGUE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_RATE ELSE NULL END)  ) *  A.ALLOCATION_LOSE ) - 1 ) * 10000 AS lose_le_ev, 

(((             ROUND(SUM(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) / SUM(CASE WHEN A.ALLOCATION_WIN = B.ALLOCATION_WIN AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) , 2 )  ) *  A.ALLOCATION_WIN ) - 1 ) * 10000 AS win_all_ev,
 
(((  ROUND( SUM(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) / SUM(CASE WHEN A.ALLOCATION_DRAW NOT IN ( 0,1 ) AND A.ALLOCATION_DRAW = B.ALLOCATION_DRAW AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) ,2 ) ) *   A.ALLOCATION_DRAW ) - 1 ) * 10000 AS draw_all_ev,

(((     ROUND(SUM(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.HIT_GAME_CNT ELSE NULL END) / SUM(CASE WHEN A.ALLOCATION_LOSE = B.ALLOCATION_LOSE AND A.BET_OPTION = B.BET_OPTION AND A.SPORT_TYPE = B.SPORT_TYPE THEN B.ALL_GAME_CNT ELSE NULL END) ,2 )  ) * A.ALLOCATION_LOSE ) - 1 ) * 10000 AS lose_le_ev, A.ROUND
        FROM
            (
                SELECT GAME_NUMBER, SPORT_TYPE, LEAGUE, BET_OPTION, ALLOCATION_WIN, ALLOCATION_DRAW, ALLOCATION_LOSE,HOME_TEAM,AWAY_TEAM,A.ROUND
                FROM kbo_stat.tb_betman_sd_game_now A 
                WHERE NOW() < A.DEADLINE_DATE
                
            ) A LEFT OUTER JOIN
            (
                SELECT SPORT_TYPE, BET_OPTION, LEAGUE, ALLOCATION_WIN, 0 AS ALLOCATION_DRAW, 0 AS ALLOCATION_LOSE
                     , COUNT(1) AS ALL_GAME_CNT
                     , SUM(CASE WHEN GAME_RESULT = '승' AND BET_OPTION IN ('승패','핸디캡','승1패','승5패','승무패','전반 승무패','전반 핸디캡','소수핸디캡') THEN 1
                                WHEN GAME_RESULT = '언더' AND BET_OPTION in ('언더오버','전반 언더오버') THEN 1 ELSE 0 END ) AS HIT_GAME_CNT
                     , ROUND( SUM(CASE WHEN GAME_RESULT = '승' AND BET_OPTION IN ('승패','핸디캡','승1패','승5패','승무패','전반 승무패','전반 핸디캡','소수핸디캡') THEN 1
                                       WHEN GAME_RESULT = '언더' AND BET_OPTION in ('언더오버','전반 언더오버')  THEN 1 ELSE 0 END ) / COUNT(1) ,2 ) AS HIT_GAME_RATE
                FROM kbo_stat.tb_betman_sd_game_result
                GROUP BY SPORT_TYPE, BET_OPTION, LEAGUE, ALLOCATION_WIN
                UNION ALL
                
                SELECT SPORT_TYPE, BET_OPTION,LEAGUE, 0 AS ALLOCATION_WIN, ALLOCATION_DRAW, 0 AS ALLOCATION_LOSE
                     , COUNT(1) AS ALL_GAME_CNT
                     , SUM(CASE WHEN GAME_RESULT = '무' AND BET_OPTION IN ('승패','핸디캡','승무패','승무패','전반 승무패','전반 핸디캡','소수핸디캡') THEN 1
                                 WHEN GAME_RESULT = '①' AND BET_OPTION = '승1패' THEN 1
                                 WHEN GAME_RESULT = '⑤' AND BET_OPTION = '승5패' THEN 1 ELSE 0 END ) AS HIT_GAME_CNT
                     , ROUND( SUM(CASE WHEN GAME_RESULT = '무' AND BET_OPTION IN ('승패','핸디캡') THEN 1
                                        WHEN GAME_RESULT = '①' AND BET_OPTION = '승1패' THEN 1
                                        WHEN GAME_RESULT = '⑤' AND BET_OPTION = '승5패' THEN 1 ELSE 0 END ) / COUNT(1) ,2 ) AS HIT_GAME_RATE
                FROM kbo_stat.tb_betman_sd_game_result
                
                GROUP BY SPORT_TYPE, BET_OPTION, LEAGUE, ALLOCATION_DRAW
                UNION ALL
                SELECT SPORT_TYPE, BET_OPTION, LEAGUE, 0 AS ALLOCATION_WIN, 0 AS ALLOCATION_DRAW, ALLOCATION_LOSE
                     , COUNT(1) AS ALL_GAME_CNT
                     , SUM(CASE WHEN GAME_RESULT = '패' AND BET_OPTION IN ('승패','핸디캡','승1패','승5패','승무패','전반 승무패','전반 핸디캡','소수핸디캡') THEN 1
                                WHEN GAME_RESULT = '오버' AND BET_OPTION in ('언더오버','전반 언더오버')   THEN 1 ELSE 0 END ) AS HIT_GAME_CNT
                     , ROUND( SUM(CASE WHEN GAME_RESULT = '패' AND BET_OPTION IN ('승패','핸디캡','승1패','승5패') THEN 1
                                       WHEN GAME_RESULT = '오버' AND BET_OPTION in ('언더오버','전반 언더오버')   THEN 1 ELSE 0 END ) / COUNT(1) ,2 ) AS HIT_GAME_RATE
                FROM kbo_stat.tb_betman_sd_game_result
                
                GROUP BY SPORT_TYPE, BET_OPTION, LEAGUE, ALLOCATION_LOSE
            ) B
            ON ( A.SPORT_TYPE = B.SPORT_TYPE
                AND A.BET_OPTION = B.BET_OPTION
                AND ( A.ALLOCATION_WIN = B.ALLOCATION_WIN OR A.ALLOCATION_DRAW = B.ALLOCATION_DRAW OR A.ALLOCATION_LOSE = B.ALLOCATION_LOSE )
                )

        GROUP BY A.GAME_NUMBER,
                 A.SPORT_TYPE,
                 A.LEAGUE,
                 A.BET_OPTION,
                 A.HOME_TEAM,
                 A.AWAY_TEAM,
                 A.ALLOCATION_WIN,
                 A.ALLOCATION_DRAW,
                 A.ALLOCATION_LOSE,A.ROUND;
